import * as C from '../constants';

// JSON data for all models: where to load their geometry and what their material is.
// @g: geometry path.
// @m: material color.
// @cs: castShadow.
// @rs: receiveShadow. 
// Note: to save storage space, the data is as concise as possible.
module.exports = {
  models: [
    // Center.
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
    },

    // First circle.
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: 1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: 1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: 1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: 0,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: -1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: -1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: -1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: -1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: 0,
    },

    // Second circle.
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -2,
      y: 2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: 2,
    },

    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: 2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 2,
      y: 2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 2,
      y: -2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: -2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: -2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: -2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -2,
      y: -2,
    },

    // Third circle.
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: 3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -2,
      y: 3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: 3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: 3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: 3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 2,
      y: 3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: 3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: 2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: 1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: 0,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: -1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: -2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: -3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 2,
      y: -3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: -3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: -3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: -3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -2,
      y: -3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: -3,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: -2,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: -1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: 0,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: 1,
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: 2,
    },


  ],
};
