import * as C from '../constants';

// JSON data for all models: where to load their geometry and what their material is.
// @g: geometry path.
// @m: material color.
// @cs: castShadow.
// @rs: receiveShadow. 
// Note: to save storage space, the data is as concise as possible.
module.exports = {
  models: [
    // Center.
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      n: 'x0y0',
    },

    // First circle.
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: 1,
      n: 'x-1y1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: 1,
      n: 'x0y1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: 1,
      n: 'x1y1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: 0,
      n: 'x1y0',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: -1,
      n: 'x1y-1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: -1,
      n: 'x0y-1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: -1,
      n: 'x-1y-1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: 0,
      n: 'x-1y0',
    },

    // Second circle.
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -2,
      y: 2,
      n: 'x-2y2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: 2,
      n: 'x-1y2',
    },

    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: 2,
      n: 'x1y2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 2,
      y: 2,
      n: 'x2y2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 2,
      y: -2,
      n: 'x2y-2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: -2,
      n: 'x1y-2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: -2,
      n: 'x0y-2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: -2,
      n: 'x-1y-2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -2,
      y: -2,
      n: 'x-2y-2',
    },

    // Third circle.
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: 3,
      n: 'x-3y3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -2,
      y: 3,
      n: 'x-2y3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: 3,
      n: 'x-1y3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: 3,
      n: 'x0y3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: 3,
      n: 'x1y3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 2,
      y: 3,
      n: 'x2y3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: 3,
      n: 'x3y3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: 2,
      n: 'x3y2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: 1,
      n: 'x3y1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: 0,
      n: 'x3y0',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: -1,
      n: 'x3y-1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: -2,
      n: 'x3y-2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 3,
      y: -3,
      n: 'x3y-3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 2,
      y: -3,
      n: 'x2y-3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 1,
      y: -3,
      n: 'x1y-3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: 0,
      y: -3,
      n: 'x0y-3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -1,
      y: -3,
      n: 'x-1y-3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -2,
      y: -3,
      n: 'x-2y-3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: -3,
      n: 'x-3y-3',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: -2,
      n: 'x-3y-2',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: -1,
      n: 'x-3y-1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: 0,
      n: 'x-3y0',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: 1,
      n: 'x-3y1',
    },
    {
      g: './models/square.json',
      m: C.NEUTRAL_SQUARE_COLOR,
      cs: true,
      rs: true,
      x: -3,
      y: 2,
      n: 'x-3y2',
    },
  ],
};
